name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read
jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          args:
            -Dsonar.projectKey=jlbermudez-imagenevolutiva_gcp_users
            -Dsonar.organization=jlbermudez-imagenevolutiva
            -Dsonar.projectBaseDir=./python
            -Dsonar.source=./python/src
            -Dsonar.tests=./python/test
            -Dsonar.verbose=true